import Providers from "@/components/provider/provider";
import "./globals.css";
import { Noto_Sans_Mono } from "next/font/google";

const noto = Noto_Sans_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${noto.className} bg-primary`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
